# Generated by Django 3.2.6 on 2021-08-25 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursos',
            old_name='sbore',
            new_name='sobre',
        ),
    ]
